---
    - name: Set hostname 
      win_hostname:
        name: '{{ domain_controller_hostname }}'
      register: winhostname
    - name: Reboot
      win_reboot:   
      when: winhostname.reboot_required
    - name: Install Active Directory roles
      win_feature: >
           name=AD-Domain-Services
           include_management_tools=yes
           include_sub_features=yes
           state=present
    - name: Create Domain
      win_domain: >
         dns_domain_name='{{ active_directory_domain_name }}'
         safe_mode_password='{{ active_directory_recovery_password }}'
      register: ad
    - name: reboot server
      win_reboot:
      when: ad.reboot_required 
    - name: Set internal DNS server 
      win_dns_client:
        adapter_names: '*'
        ipv4_addresses:
        - '127.0.0.1'
