---
    - name: win_365_intune_dev_comp_win10
      win_dsc:
        resource_name: IntuneAppProtectionPolicyiOS
        AllowedDataStorageLocations: sharePoint
        AllowedInboundDataTransferSources: managedApps
        AllowedOutboundClipboardSharingLevel: managedAppsWithPasteIn
        AllowedOutboundDataTransferDestinations: managedApps
        AppDataEncryptionType: whenDeviceLocked
        Apps: 
        Assignments: 
        ContactSyncBlocked: False
        DataBackupBlocked: False
        Description: test
        DeviceComplianceRequired: True
        DisplayName: "My DSC iOS App Protection Policy"
        ExcludedGroups:
        FingerprintBlocked: False
        ManagedBrowserToOpenLinksRequired: True
        MaximumPinRetries: 5
        MinimumPinLength: 4
        OrganizationalCredentialsRequired: False
        PeriodOfflineBeforeAccessCheck: "PT12H"
        PeriodOfflineBeforeWipeIsEnforced: "P90D"
        PeriodOnlineBeforeAccessCheck: "PT30M"
        PinCharacterSet: "alphanumericAndSymbol"
        PinRequired: True
        PrintBlocked: False
        SaveAsBlocked: True
        SimplePinBlocked: False
        Ensure: Present
        GlobalAdminAccount_username: "{{ win_365_intune_dev_comp_win10_GlobalAdminAccount_username }}"
        GlobalAdminAccount_password: "{{ win_365_intune_dev_comp_win10_GlobalAdminAccount_password }}"
