---
    - win_domain_membership:
        dns_domain_name: "{{ domain_name }}"
        domain_admin_user: "{{ domain_user }}"
        domain_admin_password: "{{ domain_user_password }}"
        domain_ou_path: "{{ domain_ou }}"
        state: domain
      register: domain_join_state

    - win_reboot:
      when: domain_join_state.reboot_required
